apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost-push-proxy.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- /* Make a deep enough copy of the default config */}}
  {{- $c := merge (dict) .Values.config }}
  {{- $_ := set $c "ListenAddress" (print ":" .Values.podPort )}}
  mattermost-push-proxy.json: {{ $c | mustToPrettyJson | b64enc }}
