name: oauth2-proxy
version: 3.2.11
apiVersion: v1
appVersion: 7.3.0
home: https://oauth2-proxy.github.io/oauth2-proxy/
description: A reverse proxy that provides authentication with Google, Github or other providers
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
sources:
  - https://github.com/phntom/charts
  - https://github.com/oauth2-proxy/oauth2-proxy
engine: gotpl
kubeVersion: ">=1.9.0-0"
