apiVersion: v1
kind: Service
metadata:
  name: {{ get (urlParse .Values.promtail.config.lokiAddress) "host" | default "loki-gateway" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loki-stack.name" . }}
    chart: {{ template "loki-stack.chart" . }}
    release: {{ .Release.Name }}
  annotations:
    {{- toYaml .Values.loki.service.annotations | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: {{ .Values.loki.service.targetPort }}
  selector:
    app: {{ default "loki" .Values.loki.nameOverride | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
