{{ $ingress := .Values.ingress }}
{{ if $ingress.enabled }}
{{ $serviceName := include "mattermost-team-edition.name" . }}
{{ $servicePort := .Values.service.externalPort }}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "mattermost-team-edition.fullname" . }}-cdn
  labels:
    app.kubernetes.io/name: {{ include "mattermost-team-edition.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "mattermost-team-edition.chart" . }}
  annotations:
    {{- if $ingress.cdn.tls }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    acme.kubernetes.io/enable: "true"
    {{- else }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end }}
    {{- with $ingress.cdn.annotations }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{ range $host := $ingress.cdn.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /static/
            backend:
        {{- if semverCompare "<1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
        {{- else }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
            pathType: Prefix
        {{- end }}
  {{ end }}
  {{ if $ingress.cdn.tls }}
  tls:
    {{- $ingress.cdn.tls | toYaml | nindent 4 }}
  {{ end }}
{{ end }}
