apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mattermost-team-edition.fullname" . }}
  labels:
    {{- include "mattermost-team-edition.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
