apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mattermost-team-edition.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mattermost-team-edition.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: metrics
      interval: 30s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "mattermost-team-edition.selectorLabels" . | nindent 6 }}
