{{- $fullName := include "binaryvision-static-wordpress.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: nix-co-il-redirect
  annotations:
    acme.kubernetes.io/enable: "true"
    acme.kubernetes.io/dns: "dns_cf"
    nginx.ingress.kubernetes.io/permanent-redirect: https://kix.co.il/signup_user_complete/?id=hiyeztycyidz9ja4gx6bw18p3h
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location = /robots.txt {
        add_header Content-Type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
      }

spec:
  tls:
    - hosts:
        - nix.co.il
        - join.nix.co.il
        - www.nix.co.il
        - web.nix.co.il
        - webchat.nix.co.il
        - chat.kix.co.il
      secretName: nix-co-il-redirect-tls
  rules:
    - host: join.nix.co.il
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    - host: webchat.nix.co.il
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    - host: chat.kix.co.il
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
