apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "camo.fullname" . }}
data:
  PORT: {{ .Values.camo.port | default 8081 | toString | b64enc | quote }}
  CAMO_HEADER_VIA: {{ .Values.camo.headers.userAgent | default (printf "Camo Asset Proxy %s" .Chart.AppVersion) | b64enc | quote }}
  CAMO_KEY: {{ .Values.camo.key | b64enc | quote }}
  CAMO_LENGTH_LIMIT: {{ .Values.camo.limits.maxContentLength | toString | b64enc | quote }}
  CAMO_LOGGING_ENABLED: {{ ternary "debug" "disabled" .Values.camo.debug | b64enc | quote }}
  CAMO_MAX_REDIRECTS: {{ .Values.camo.limits.maxRedirects | toString | b64enc | quote }}
  CAMO_SOCKET_TIMEOUT: {{ .Values.camo.limits.socketTimeoutSeconds | toString | b64enc | quote }}
  CAMO_TIMING_ALLOW_ORIGIN: {{ .Values.camo.headers.timingAllowOrigin | default "" | b64enc | quote }}
  CAMO_HOSTNAME: {{ .Values.camo.headers.hostname | default "unknown" | b64enc | quote }}
  CAMO_KEEP_ALIVE: {{ .Values.camo.headers.keepAlive | default false | toString | b64enc | quote }}
