apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "external-dns-host-network.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "external-dns-host-network.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "external-dns-host-network.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
