apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-host-network.fullname" . | quote }}
  labels:
  {{- include "external-dns-host-network.labels" . | nindent 4 }}
type: Opaque
data:
  LINODE_CLI_TOKEN: {{ .Values.settings.linode.token | b64enc | quote }}
  CLOUDFLARE_TOKEN: {{ .Values.settings.cloudflare.token | b64enc | quote }}
