dependencies:
  - name: postgresql
    version: 12.0.0
    condition: postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: mariadb
    version: 11.3.3
    condition: mariadb.enabled
    repository: https://charts.bitnami.com/bitnami
