apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mindav.fullname" . | quote }}
  namespace: {{ .Release.Namespace }}
data:
  .env.json: |
    {
      {{- with .Values.mindav.webdav }}
      "WEBDAV_DRIVER": {{ .driver | quote }},
      "WEBDAV_USER": {{ .user | quote }},
      "WEBDAV_PASSWORD": {{ .password | quote }},
      {{- end }}
      {{- with .Values.mindav.minio }}
      "MINIO_ENDPOINT": {{ .endpoint | quote }},
      "MINIO_ACCESS_KEY_ID": {{ .key | quote }},
      "MINIO_SECRET_ACCESS_KEY": {{ .secret | quote }},
      "MINIO_BUCKET": {{ .bucket | quote }},
      "MINIO_USE_SSL": {{ .ssl }},
      "MEMORY_UPLOAD_MODE": {{ .memoryUpload }},
      {{- end }}
      "APP_DEBUG": {{ .Values.mindav.debug }},
      "APP_PORT": {{ .Values.service.containerPort }}
    }
