{{- if .Values.ingress.enabled -}}
{{- $fullName := include "mindav.fullname" . }}
{{- $svcPort := .Values.service.port }}
{{- if semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: extensions/v1beta1
{{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-mobile
  labels:
  {{- include "mindav.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /v1/webdav/$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-URI-Prefix "https://{{ .Values.ingress.host.host }}/{{ .Values.ingress.host.mobilePath }}";
      proxy_set_header X-Auth-Request-User "kixtoken@";
      set $testauth x$http_authorization;
      if ($testauth = x) {
        more_set_headers "WWW-Authenticate: Basic realm=\"Authentication Required - Personl Access Token from kix.co.il\"";
        return 401 Unauthorized;
      }
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host.host | quote }}
      http:
        paths:
          - path: "{{ .Values.ingress.host.mobilePath }}/(.*)"
            pathType: Exact
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
{{- end }}
