apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "mindav.fullname" . }}
data:
  WEBDAV_USER: {{ .Values.mindav.webdav.user | b64enc | quote }}
  WEBDAV_PASSWORD: {{ .Values.mindav.webdav.password | b64enc | quote }}
  MINIO_ACCESS_KEY_ID: {{ .Values.mindav.minio.key | b64enc | quote }}
  MINIO_SECRET_ACCESS_KEY: {{ .Values.mindav.minio.secret | b64enc | quote }}
